#!/bin/bash

pokemon_list=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")

for pokemon in "${pokemon_list[@]}"
do
  URL="https://pokeapi.co/api/v2/pokemon/$pokemon"
  echo $pokemon
    RESPONSE=$(curl --request GET \
        --url $URL \
        -w "\n%{http_code}" \
        -s)
        echo "Fetching data for $pokemon ..."
        sleep 1s
        file=pokemon_data/$pokemon.json
        sed '$ d' <<< "$RESPONSE" > $file
        echo "Saved data to $file ✅"
done