#!/bin/bash


sum_height=0
sum_wight=0

output_file="pokemon_report.csv"
echo "Name,Height (m),Weight (kg)" > "$output_file"

for FILE in "pokemon_data/"*; do
    ((pokemon_num++))
    name=$(jq -r '.name' $FILE)
    formatted_height=$(jq -r '.height' $FILE | awk '{print $1/10}')
    formatted_weight=$(jq -r '.weight' $FILE | awk '{print $1/10}')
    echo "$name,${formatted_height},${formatted_weight}" >> "$output_file"
    sum_height=$(echo "$sum_height + $formatted_height" | bc -l)
    sum_wight=$(echo "$sum_wight + $formatted_weight" | bc -l)
done

sum_height=$(echo "scale=2; $sum_height / $pokemon_num" | bc -l)
average_wight=$(echo "scale=2; $sum_wight / $pokemon_num" | bc -l)

echo "CSV Report generated at: $output_file"
echo
cat "$output_file"
echo
echo "Average Height: ${avg_height} m"
echo "Average Weight: ${avg_weight} kg"

